services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-netvaerke}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-abc123}
      POSTGRES_DB: ${POSTGRES_DB:-netvaerke}
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER:-netvaerke} -d ${POSTGRES_DB:-netvaerke}
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    networks:
      - default
    volumes:
      - db_data:/var/lib/postgresql/data

  liquibase:
    build:
      context: ./liquibase
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-netvaerke}
      LIQUIBASE_COMMAND_USERNAME: ${POSTGRES_USER:-netvaerke}
      LIQUIBASE_COMMAND_PASSWORD: ${POSTGRES_PASSWORD:-abc123}
    networks:
      - default

  nats:
    image: nats:2.12.11-alpine
    ports:
      - "4222:4222"
      - "8222:8222"

# hanko services
  postgres_hanko:
    image: postgres:17-alpine
#    ports:
#      - "5433:5432"
    environment:
      - POSTGRES_USER=hanko
      - POSTGRES_PASSWORD=hanko
      - POSTGRES_DB=hanko
    healthcheck:
      test: pg_isready -U hanko -d hanko
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - default
    volumes:
      - hanko_data:/var/lib/postgresql/data

  hanko-migrate:
    image: ghcr.io/teamhanko/hanko:latest
    depends_on:
      postgres_hanko:
        condition: service_healthy
    volumes:
      - ./hanko-config.yaml:/etc/hanko/config.yaml:ro,z
    command: --config /etc/hanko/config.yaml migrate up

  hanko:
    image: ghcr.io/teamhanko/hanko:latest
    depends_on:
      hanko-migrate:
        condition: service_completed_successfully
    ports:
      - "8000:8000"  # Public API
      - "8001:8001"  # Admin API
    volumes:
      - ./hanko-config.yaml:/etc/hanko/config.yaml:ro,z
    command: serve --config /etc/hanko/config.yaml all

  mailslurper:
    image: marcopas/docker-mailslurper:latest
    ports:
      - '8090:8080' # web UI
      - '8085:8085'
    networks:
      - default

networks:
  default:
    name: netvaerke

volumes:
  db_data:
  hanko_data:
