database:
  user: hanko
  password: hanko
  host: postgres_hanko
  port: 5432
  dialect: postgres
email_delivery:
  smtp:
    host: "mailslurper"
    port: "2500"
  from_address: noreply@hanko.io
cors:
  allow_origins:
    - "http://localhost:8000"
    - "http://localhost:8080"
    - "http://localhost"
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: Hanko Authentication Service
webauthn:
  relying_party:
    origins:
      - "http://localhost:8000"
      - "http://localhost:8080"
      - "http://localhost"
session:
  enable_auth_token_header: true
  cookie:
    secure: false # is needed for safari, because safari does not store secure cookies on localhost
