modules:
  - access/contact-access
  - access/profile-access
  - access/tenant-access
  - businesslogic/membership-manager
  - businesslogic/network-manager
  - ui/web
  - utilities/ifx
  - utilities/test-support
