modules:
  - access/contact-access
  - access/engagement-access
  - access/profile-access
  - access/tenant-access
  - businesslogic/authorization-engine
  - businesslogic/membership-manager
  - businesslogic/network-manager
  - subsystems/membership-manager-application
  - subsystems/network-manager-application
  - ui/web
  - utilities/ifx
  - utilities/test-support
