include:
  - ../../docker-compose.yaml

services:
#  web:
#    build:
#      context: ../..
#      dockerfile: ui/web/Dockerfile
#    restart: unless-stopped
#    depends_on:
#      membership-manager:
#        condition: service_started
#      hanko:
#        condition: service_started
#    ports:
#      - "8080:8080"
#    environment:
#      NATS_URL: nats://nats:4222
#      MEMBERSHIP_NATS_SUBJECT: ${MEMBERSHIP_NATS_SUBJECT:-netvaerke.membership-manager.v1}
#      MEMBERSHIP_NATS_TIMEOUT_SECONDS: ${MEMBERSHIP_NATS_TIMEOUT_SECONDS:-5}
#      HANKO_API_URL: ${HANKO_API_URL:-http://localhost:8000}
#      HANKO_VALIDATION_API_URL: http://hanko:8000
#      HANKO_COOKIE_DOMAIN: ${HANKO_COOKIE_DOMAIN:-}
#      SECURE_COOKIES: ${SECURE_COOKIES:-false}

  membership-manager:
    build:
      context: ../..
      dockerfile: businesslogic/membership-manager/Dockerfile
    restart: unless-stopped
    depends_on:
      liquibase:
        condition: service_completed_successfully
      nats:
        condition: service_started
    environment:
      DATABASE_URL: jdbc:postgresql://db:5432/${POSTGRES_DB:-netvaerke}
      DATABASE_USER: ${POSTGRES_USER:-netvaerke}
      DATABASE_PASSWORD: ${POSTGRES_PASSWORD:-abc123}
      NATS_URL: nats://nats:4222
      MEMBERSHIP_NATS_SUBJECT: ${MEMBERSHIP_NATS_SUBJECT:-netvaerke.membership-manager.v1}
      MEMBERSHIP_NATS_QUEUE_GROUP: ${MEMBERSHIP_NATS_QUEUE_GROUP:-netvaerke.membership-manager.v1}
      MEMBERSHIP_NATS_TIMEOUT_SECONDS: ${MEMBERSHIP_NATS_TIMEOUT_SECONDS:-5}
